### ISSUE TITLE
Stability?

### ISSUE THREAD

**Issue by jakubka** [afacanerman/api-valter#6]
Hey,

Thanks for the project. Just a quick question.. do you consider it stable? Is it used by any system in production?

Also, do I understand correctly that only nodejs APIs are supported? Or it is possible to validate contracts of any API (basically perform real requests agains the endpoint)?

Thanks!

Jakub

**Comment by afacanerman** [comment]
Hi,

While I was working in Hepsiburada.com (biggest e-commerce web site in Turkey) It was being used in continuous delivery pipelines in order to fulfill contract testing between any kind web API. It validates any kind API's contract the thing is you need to provide .contract file in JSON format. 

cheers

**Comment by jakubka** [comment]
Thanks for prompt response!

In README it says that validation is run like this:

`api-valter-directory$ node app.js -p "/contract-directory"`

I would assume that a base URL of the API will have to be specified. How else can it tell which API to check?

One more question regarding stability... are you still working on this project? Do you plan to enhance it further?

Thanks,

Jakub

**Comment by afacanerman** [comment]
This is example .contract file replace fields in bold
{
    "producer": "**replace with your api baseurl**",
    "for": "description",
    "on": "**GET**", 
    "uri": "/**replace with your api endpoint**",
    "expect": {
        "request": {
            "status_code": 200,
            "headers": []
        },
        "body": {
            "yourApiDataResponseObj": **paste your api endpoint response**
        }
    }
}

I would like to help you if you have problem to be honest this project is not my top priority. You can always contribute.

**Comment by jakubka** [comment]
Ah thanks, I didn't see that base url is provided in the .contract file.

Thanks for your help!
